# Generated by Django 5.0.6 on 2024-06-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('person_max', models.IntegerField(default=0, verbose_name='Макс количество взрослых')),
                ('child_max', models.IntegerField(default=0, verbose_name='Макс количество детей')),
                ('room_class', models.IntegerField(default=0, verbose_name='Тип номера')),
                ('room_number', models.IntegerField(default=0, verbose_name='Номер комнаты')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'db_table': 'Rooms',
            },
        ),
    ]
